name: Build test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CLone source
      run: |
        git clone --recursive https://github.com/JingOS-team/JingOS.git